import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "RepoSmart - Smart GitHub Repository Evaluator",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full">{children}</body>
    </html>
  );
}
