import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import GoogleProvider from "@/providers/googleProvider";

export const metadata: Metadata = {
  title: "RepoSmart - Smart GitHub Repository Evaluator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full">
        <GoogleProvider>{children}</GoogleProvider>
      </body>
    </html>
  );
}
